<?php
/**
 * Magento CardGatePlus payment extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category    Mage
 * @package     CardGate_Payment
 * @author      Richard Schoots, <support@cardgate.com>
 * @copyright   Copyright (c) 2015 CardGatePlus B.V. (http://www.cardgateplus.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $_code=$this->getMethodCode() ?>

<ul class="form-list checkout-agreements" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <?php if ($this->getinstructions() ){ ?>
        <div class="banktransfer-instructions-content agreement-content">
            <?php echo $this->getInstructions(); ?>
        </div>
        <?php } ?>
    </li>
</ul>

